name: shop_radar_assistant
description: 自動偵測周邊店家並快速開啟行動支付與載具的行動助手。
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  geofence_service: ^6.0.0+1
  geolocator: ^10.1.1
  fl_location: ^3.1.0 
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true